# ########################################
# A persistent volume claim (PVC) specifies the desired access mode and storage capacity. 
# Currently, based on only these two attributes, a PVC is bound to a single PV. Once a PV 
# is bound to a PVC, that PV is essentially tied to the PVC’s project and cannot be bound 
# to by another PVC. There is a one-to-one mapping of PVs and PVCs. 
# However, multiple pods in the same project can use the same PVC.
# ########################################
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gluster-claim  
spec:
  accessModes:
  - ReadWriteMany      
  resources:
     requests:
       storage: 1Gi

