apiVersion: v1
kind: Endpoints
metadata:
  name: gluster-cluster 
subsets:
- addresses:              
  - ip: {IP-NODE-1}
  ports:                  
  - port: 1
    protocol: TCP
- addresses:
  - ip: {IP-NODE-2}
  ports:
  - port: 1
    protocol: TCP
    
    